name: Test ARM64 Fix
on:
  push:
    branches: [ fix-arm64-sqlite ]
  workflow_dispatch:

jobs:
  test-arm64-rebuild:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Test rebuild with TARGET_ARCH
        env:
          TARGET_ARCH: arm64
        run: |
          echo "Testing electron-rebuild with TARGET_ARCH=arm64"
          pnpm postinstall
          echo "Checking better-sqlite3 architecture:"
          file apps/desktop/node_modules/better-sqlite3/build/Release/better_sqlite3.node || echo "File not found"
      - name: Test desktop build
        env:
          TARGET_ARCH: arm64
        run: |
          echo "Testing desktop build"
          pnpm run --filter desktop build